In [6]:
import pandas as pd
import numpy as ny
import matplotlib.pyplot as plt
import math
from sklearn import linear_model
import word2number

# LINEAR REGRESSION WITH MULTIPLE VARIABLE

In [7]:
d=pd.read_csv('d://homeprices.csv')
d

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  565000
4  4000       5.0    8  760000

In [8]:
med=math.floor(d.bedrooms.median())
med

3

In [9]:
d.bedrooms=d.bedrooms.fillna(med)
d

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  565000
4  4000       5.0    8  760000

In [10]:
reg=linear_model.LinearRegression()

In [11]:
reg

LinearRegression()

In [12]:
reg.fit(d[['area','bedrooms','age']],d.price)
reg

LinearRegression()

In [13]:
reg.predict([[3000,3,15]])

array([623275.])

In [14]:
reg.coef_

array([   129.75, -34275.  ,  -9075.  ])

In [15]:
reg.intercept_

472974.9999999996

In [16]:
reg.coef_[0]

129.75000000000009

In [17]:
def predict(reg,val):
    return reg.coef_[0]*val[0]+reg.coef_[1]*val[1]+reg.coef_[2]*val[2]+reg.intercept_

In [18]:
predict(reg,[4000,3,12])

780250.0

In [19]:
#EXCERCISE

In [20]:
d=pd.read_csv('d://hiring.csv')
def trans(x):
    if(x=='zero'):
        return 0
    elif(x=='one'):
        return 1
    elif(x=='two'):
        return 2
    elif(x=='three'):
        return 3
    elif(x=='four'):
        return 4
    elif(x=='five'):
        return 5
    elif(x=='six'):
        return 6
    elif(x=='seven'):
        return 7
    elif(x=='eight'):
        return 8
    elif(x=='nine'):
        return 9
    elif(x=='ten'):
        return 10
    elif(x=='eleven'):
        return 11
d

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [21]:
d.experience=d.experience.fillna('zero')
d.test_score=d.test_score.fillna(math.floor(d.test_score.median()))
d.experience=d.experience.apply(trans)
d

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [22]:
reg=linear_model.LinearRegression()
reg

LinearRegression()

In [23]:
reg.fit(d[['experience','test_score','interview_score']],d.salary)
reg

LinearRegression()

In [24]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [25]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [26]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [27]:
reg.intercept_
reg

LinearRegression()

In [28]:
import pickle

In [29]:
with open('d://ML_MODELS/linear_reg','wb') as f:
    pickle.dump(reg)

TypeError: dump() missing required argument 'file' (pos 2)